apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/instance: redis
      app.kubernetes.io/name: redis
