apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-share-groundfish-pvc-3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${APP_SHARE_SIZE}
  storageClassName: ""
  volumeName: pv-app-share-groundfish-3
