apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-node
spec:
  template:
    spec:
      containers:
      - name: redis
        env:
          - name: REDIS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      - name: sentinel
        env:
          - name: REDIS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
